# -*- coding: utf-8 -*-
"""Zomato_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPJ2uHd6kMFkVsaclkj8XinHZo94-NAw

Data Analysis on the dataset available with us for the Zomato

Importing all the important libraries required
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importing the dataset for the zomato"""

dataframe = pd.read_csv("zomato_data.csv")
print(dataframe.head())

def handleRate(value):
    value=str(value).split('/')
    value=value[0];
    return float(value)

"""Applying rating and checking it for different kind of restaurants"""

dataframe['rate']=dataframe['rate'].apply(handleRate)
print(dataframe.head())

"""Getting basic information from the given dataset"""

dataframe.info()

"""Plotting the graph for count vs type of restaurants"""

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel("Type of restaurant")

"""Making plot to demonstrates the voting given to the different types of restaurants"""

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c='green', marker='o')
plt.xlabel('Type of restaurant', c='red', size=20)
plt.ylabel('Votes', c='red', size=20)

max_votes = dataframe['votes'].max()
restaurant_with_max_votes = dataframe.loc[dataframe['votes'] == max_votes, 'name']

"""Computing the maximum votes"""

print('Restaurant(s) with the maximum votes:')
print(restaurant_with_max_votes)

"""Plot for count vs online_order"""

sns.countplot(x=dataframe['online_order'])

"""Plotting histogram to visualize the rating distributions"""

plt.hist(dataframe['rate'],bins=5)
plt.title('Ratings Distribution')
plt.show()

"""Using the plot, finding the plot for approx cost for two peoples."""

couple_data=dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""Plotting the plot between online_order vs rate to get the better analysis insights"""

plt.figure(figsize = (6,6))
sns.boxplot(x = 'online_order', y = 'rate', data = dataframe)

"""Drawing the heatmap to get the better visualization"""

pivot_table = dataframe.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap='YlGnBu', fmt='d')
plt.title('Heatmap')
plt.xlabel('Online Order')
plt.ylabel('Listed In (Type)')
plt.show()